#!/usr/bin/env bash
# Wire .env + infra/Caddyfile for HTTPS/WSS via Caddy + Let's Encrypt.
# Requires a real domain (A/AAAA → VM). For bare public-IP HTTP, use configure-public-ip.sh instead.
#
# Usage:
#   DOMAIN=class.example.com PUBLIC_IP=203.0.113.10 ./scripts/configure-domain-tls.sh
#   DOMAIN=class.example.com PUBLIC_IP=203.0.113.10 ACME_EMAIL=you@example.com ./scripts/configure-domain-tls.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
CADDYFILE="$ROOT/infra/Caddyfile"

if [[ -z "${DOMAIN:-}" || -z "${PUBLIC_IP:-}" ]]; then
  echo "Usage: DOMAIN=<hostname> PUBLIC_IP=<vps-public-ip> $0" >&2
  echo "Example: DOMAIN=class.example.com PUBLIC_IP=203.0.113.10 ACME_EMAIL=admin@example.com $0" >&2
  echo >&2
  echo "Let's Encrypt needs a domain pointed at this VM." >&2
  echo "For bare public-IP HTTP (no TLS): PUBLIC_IP=… ./scripts/configure-public-ip.sh" >&2
  exit 1
fi

# Strip scheme/path if someone pastes a URL
DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%%/*}"
DOMAIN="${DOMAIN%%:*}"

LIVEKIT_HOST="${LIVEKIT_HOST:-livekit.${DOMAIN}}"
ACME_EMAIL="${ACME_EMAIL:-}"

if [[ ! -f "$ENV_FILE" ]]; then
  cp "$ROOT/.env.example" "$ENV_FILE"
  echo "Created $ENV_FILE from .env.example"
fi

upsert() {
  local key="$1" val="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    awk -v k="$key" -v v="$val" 'BEGIN{FS=OFS="="} $1==k {$0=k"="v} {print}' "$ENV_FILE" > "$ENV_FILE.tmp"
    mv "$ENV_FILE.tmp" "$ENV_FILE"
  else
    echo "${key}=${val}" >> "$ENV_FILE"
  fi
}

APP_URL_VAL="https://${DOMAIN}"
LK_URL="wss://${LIVEKIT_HOST}"

upsert DOMAIN "$DOMAIN"
upsert PUBLIC_IP "$PUBLIC_IP"
upsert APP_URL "$APP_URL_VAL"
upsert NEXT_PUBLIC_APP_URL "$APP_URL_VAL"
upsert NEXT_PUBLIC_LIVEKIT_URL "$LK_URL"
# Server→LiveKit stays on loopback (host networking)
upsert LIVEKIT_URL "ws://127.0.0.1:7880"
upsert LIVEKIT_INTERNAL_URL "http://127.0.0.1:7880"
upsert LIVEKIT_USE_EXTERNAL_IP "true"
upsert LIVEKIT_NODE_IP "$PUBLIC_IP"
upsert COOKIE_SECURE "true"
if [[ -n "$ACME_EMAIL" ]]; then
  upsert ACME_EMAIL "$ACME_EMAIL"
fi

# Write Caddyfile with concrete hostnames
EMAIL_LINE="# email admin@example.com  # set ACME_EMAIL=… when running configure-domain-tls.sh"
if [[ -n "$ACME_EMAIL" ]]; then
  EMAIL_LINE="email ${ACME_EMAIL}"
fi

cat > "$CADDYFILE" << CADDY
# Caddy reverse proxy + automatic HTTPS (Let's Encrypt).
# Generated by scripts/configure-domain-tls.sh — re-run after DOMAIN / ACME_EMAIL changes.
#
# DNS required:
#   ${DOMAIN}         A/AAAA → ${PUBLIC_IP}
#   ${LIVEKIT_HOST}   A/AAAA → ${PUBLIC_IP}
#
# Bring up with TLS profile:
#   docker compose --profile tls up --build -d
#
# Firewall: open 80/tcp, 443/tcp, 7881/tcp, 50000–50100/udp.
# Do NOT expose 3000 or 7880 publicly when using Caddy (signaling via WSS on livekit host).
# Media (WebRTC UDP/TCP) stays direct to LiveKit — Caddy cannot terminate UDP.

{
	${EMAIL_LINE}
}

${DOMAIN} {
	encode gzip
	reverse_proxy 127.0.0.1:3000
}

${LIVEKIT_HOST} {
	encode gzip
	# WebSocket upgrade is automatic in Caddy
	reverse_proxy 127.0.0.1:7880
}
CADDY

echo "Updated .env and infra/Caddyfile for HTTPS domain ${DOMAIN}:"
echo "  APP_URL=${APP_URL_VAL}"
echo "  NEXT_PUBLIC_LIVEKIT_URL=${LK_URL}"
echo "  COOKIE_SECURE=true"
echo "  LIVEKIT_USE_EXTERNAL_IP=true"
echo "  LIVEKIT_NODE_IP=${PUBLIC_IP}"
[[ -n "$ACME_EMAIL" ]] && echo "  ACME_EMAIL=${ACME_EMAIL}"
echo
echo "DNS (required for Let's Encrypt):"
echo "  ${DOMAIN}         → ${PUBLIC_IP}  (A or AAAA)"
echo "  ${LIVEKIT_HOST}   → ${PUBLIC_IP}  (A or AAAA)"
echo
echo "Next:"
echo "  ./scripts/sync-livekit-keys.sh"
echo "  docker compose --profile tls up --build -d"
echo
echo "Firewall reminder (with Caddy):"
echo "  Open:  80/tcp, 443/tcp, 7881/tcp, 50000-50100/udp"
echo "  Close publicly: 3000/tcp, 7880/tcp (proxied via Caddy), 5432, 6379"
echo "See docs/DEPLOY-CADDY.md"
