#!/usr/bin/env bash
# Generate infra/livekit.yaml (untracked) from .env: API key/secret + RTC
# public-IP settings.
#
# - Creates .env from .env.example when missing.
# - Replaces missing / placeholder / known-leaked LIVEKIT_API_KEY,
#   LIVEKIT_API_SECRET, NEXTAUTH_SECRET and POSTGRES_PASSWORD with fresh random
#   values (written only to .env, never printed). ROTATE_SECRETS=1 forces new ones.
# - Never writes secrets to a tracked file. infra/livekit.example.yaml is the
#   tracked template; infra/livekit.yaml is gitignored.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/infra/livekit.yaml"
TEMPLATE="$ROOT/infra/livekit.example.yaml"

# shellcheck source=lib/secrets.sh
source "$ROOT/scripts/lib/secrets.sh"

if [[ ! -f "$ENV_FILE" ]]; then
  cp "$ROOT/.env.example" "$ENV_FILE"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
  echo "Created .env from .env.example"
fi

ensure_env_secrets "$ENV_FILE"
assert_env_secrets "$ENV_FILE"

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

USE_EXT="${LIVEKIT_USE_EXTERNAL_IP:-false}"
# Auto-enable external IP when APP_URL / NEXT_PUBLIC_APP_URL points at a non-loopback host
APP="${APP_URL:-${NEXT_PUBLIC_APP_URL:-}}"
if [[ "$USE_EXT" != "true" && -n "$APP" ]]; then
  case "$APP" in
    *localhost*|*127.0.0.1*|*::1*) ;;
    http://*|https://*) USE_EXT=true ;;
  esac
fi

NODE_IP_LINE=""
if [[ -n "${LIVEKIT_NODE_IP:-}" ]]; then
  NODE_IP_LINE="  node_ip: ${LIVEKIT_NODE_IP}"
fi

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Missing $TEMPLATE" >&2
  exit 1
fi

umask 077
TMP="$(mktemp "$OUT.XXXXXX")"
# Fill the template. Values are passed through the environment (not argv) so
# they never show up in `ps`.
LK_KEY="$LIVEKIT_API_KEY" LK_SECRET="$LIVEKIT_API_SECRET" LK_USE_EXT="$USE_EXT" LK_NODE_IP_LINE="$NODE_IP_LINE" \
  awk '
    BEGIN { print "# GENERATED by scripts/sync-livekit-keys.sh from .env. Contains the LiveKit"; print "# API secret (admin credential). Gitignored: never commit this file."; header = 1 }
    header && /^#/ { next }
    { header = 0 }
    /__NODE_IP_LINE__/ { if (ENVIRON["LK_NODE_IP_LINE"] != "") print ENVIRON["LK_NODE_IP_LINE"]; next }
    {
      gsub(/__USE_EXTERNAL_IP__/, ENVIRON["LK_USE_EXT"])
      gsub(/__LIVEKIT_API_KEY__/, ENVIRON["LK_KEY"])
      gsub(/__LIVEKIT_API_SECRET__/, ENVIRON["LK_SECRET"])
      print
    }
  ' "$TEMPLATE" > "$TMP"
# LiveKit runs as a non-root user in its container and must be able to read it.
chmod 644 "$TMP"
mv "$TMP" "$OUT"

echo "Wrote infra/livekit.yaml (untracked; use_external_ip=${USE_EXT}${LIVEKIT_NODE_IP:+, node_ip=${LIVEKIT_NODE_IP}})"
echo "Restart LiveKit and web after a key change: docker compose up -d --force-recreate livekit web"
